.TH man 1 "{{build_date}}" "{{version}}" "venom man page"

.SH NAME
venom \- GNOME Themes for Debian-8 system

.SH SYNOPSIS
.B
venom 
list

.B
venom
use [NAME]

.SH DESCRIPTION
venom is package contains themes with mono-color, high-contrast,
no-border-radius, no-shadow. It also contains tool called venom to
apply themes. It change GTK-3 theme, GNOME, metacity, icons and
wallpaper.

It is help people focus on work, without effected from
complicated things. And it also improve performance of GNOME as a result.

.B
venom list 
show them names.
.B
venom use
active theme by name.

.SH CMD-USE
.TP 4
Use theme by name. Name must be one of
black
.br
orange
.br
green
.TP
Example

$ venom use black

.SH FILES
For each path to file below,
.B
<name>
is theme name, specify in CMD-USE section.

.TP 4
/usr/share/themes/<name>/theme.conf
Configurations of theme.

.TP
/usr/share/themes/<name>/gtk-3.0/
Directory contains asset of GTK-3.0 theme.

.TP
/usr/share/themes/<name>/gtk-2.0/
Directory, it isn't contains any thing, but it is required to system
realize GTK-3.0 theme.

.TP
/usr/share/themes/<name>/gnome-shell/
Directory contains asset of GNOME-3.14.x theme.

.TP
/usr/share/themes/<name>/metacity-1
Directory contains asset of window decoration.

.TP
/usr/share/icons/<name>/
Directory contains icons of theme.

.SH SEE ALSO
Venom repository at https://github.com/kevin-leptons/venom.

.SH BUGS
Depend on user's perspective.

.SH AUTHOR
Kevin Leptons <kevin.leptons@gmail.com>
